### ISSUE TITLE
libcamera failing to write image file

### ISSUE THREAD

**Issue by TexasTNT** [raspberrypi/libcamera-apps#265]
I am having issues with libcamera on my allsky software and [@EricClaeys](https://github.com/EricClaeys) supports, and suggested I create an Issue.

some times it will capture a few frames then quits or just won't capture at all.
attaching the config.txt file, output of free, output of uname also attached output of running libcamera-hello, libcamera-jpeg and libcamera-still.

Thanks for the Help!
Norman
[libcamera output.txt](https://github.com/raspberrypi/libcamera-apps/files/8147373/libcamera.output.txt)
[libcamera-still output.txt](https://github.com/raspberrypi/libcamera-apps/files/8147374/libcamera-still.output.txt)
[uname.txt](https://github.com/raspberrypi/libcamera-apps/files/8147375/uname.txt)
[config.txt](https://github.com/raspberrypi/libcamera-apps/files/8147376/config.txt)
[free.txt](https://github.com/raspberrypi/libcamera-apps/files/8147377/free.txt)

**Comment by davidplowman** [comment]
Hi, thanks for reporting this. Could you try deleting the `gpu_mem` line from your config.txt? libcamera uses CMA memory, not gpu_mem, so defining a large amount like this is actually quite harmful, it's best to leave it to the system to decide.

**Comment by TexasTNT** [comment]
Hello
That helped, takes about 20 images and then fails to save them.
Thanks for the Help!
Norman
[libcamera output-2.txt](https://github.com/raspberrypi/libcamera-apps/files/8154575/libcamera.output-2.txt)
[allsky.log](https://github.com/raspberrypi/libcamera-apps/files/8154576/allsky.log)
.

**Comment by davidplowman** [comment]
Glad that it's behaving better, but it still doesn't really seem right to me. You ought to be able run libcamera-still over and over indefinitely, so there's still something to look at. Is it the same error message about not being able to allocate buffers? It might be worth opening another terminal window, typing `watch -n 1 cat /proc/meminfo` and watching for it to fail...

**Comment by TexasTNT** [comment]
Is it the same error message about not being able to allocate buffers? -Yes
well the watch -n 1 cat /proc/meminfo won't run says "not found"

**Comment by TexasTNT** [comment]
ok operator error, got to run but what am i looking for?
doesn't look like anything over running.

**Comment by davidplowman** [comment]
I've fished out an old Pi 3 and have seen the same thing when I run libcamera-jpeg in a simple loop. It seems to fail after just a few captures. By contrast my Pi 4 runs forever (well, 24 hours, with no problems) so there's evidently something wrong on the Pi 3. We'll have to investigate.

**Comment by davidplowman** [comment]
Investigations so far suggest that it is indeed a CMA memory problem. The problem may be to do with the graphics system using the same memory and causing some degree of fragmentation, which can interfere with the camera system's ability to allocate the large chunks it needs for HQ camera images. It causes a problem even if you're not displaying a preview window from the camera application (though doing so probably makes it worse).

The best workaround for this for most people is likely to be the following.

- In your /boot/config.txt, find the line that says `dtoverlay=vc4-kms-v3d` and change it to `dtoverlay=vc4-kms-v3d,cma-384`. This will give you 384MB of CMA (rather than the default 256MB) which seems to be sufficient on my Pi 3 to enable the camera to run indefinitely.

If you are unable to make the above change, some other alternatives might include the following, but they possibly won't be applicable in all circumstances and to all users:

- Don't run X Windows. If you don't run X Windows then there is simply no problem at all.
- Disable Glamor again (which you probably re-enabled in the first place). It means the standard OpenGL preview implementation won't work, but if you're not using a preview window this would probably resolve the problem for you.

**Comment by TexasTNT** [comment]
Hello
Made the change dtoverlay=vc4-kms-v3d,cma-384 and no change same errors about buffers.
Disabled Glamor no help.
Would the size of the swapfile cause any issues its 2gig?
Thanks for the Help!
Norman

**Comment by TexasTNT** [comment]
OK here is what I have - see libcamera Test-1.txt

How many runs does this manage before it fails? - see libcamera Test-1.txt

Then please try it with cma-384. - see libcamera Test-2.txt

 try it without X Windows - 3 time then got same errors as previous tests.
also attached my script and the log.txt
Thanks for the Help!
Norman
[libcamera Test-2.txt](https://github.com/raspberrypi/libcamera-apps/files/8173725/libcamera.Test-2.txt)
[log.txt](https://github.com/raspberrypi/libcamera-apps/files/8173726/log.txt)
[libcamera Test-1.txt](https://github.com/raspberrypi/libcamera-apps/files/8173727/libcamera.Test-1.txt)
[lctst.sh.txt](https://github.com/raspberrypi/libcamera-apps/files/8173729/lctst.sh.txt)

**Comment by davidplowman** [comment]
Thanks for doing all that. A few things I notice:

- There are quite a few segfaults. That's been fixed but I'll get that pushed up to our apt repository.
- "libcamera Test-2.txt" doesn't show any more CMA than the previous one (bottom 2 lines of /proc/meminfo). Can you share your /boot/config.txt file?
- "log.txt" simply shows that someone else is holding the camera and we can't open it.

Unfortunately we'll probably need to try all this again once the segfaults are sorted, we figure out why the CMA isn't increasing, and why someone else has the camera open. Anyway, if you can post your /boot/config.txt that may help answer the second of these questions, and I'll let you know when the version in apt is updated.

**Comment by TexasTNT** [comment]
attaching files from some more tests, I have added my notes.
I have decreased the swap to 1gig and stopped allsky, the script ran 550 times before I stopped it. longest run with no segfault was 21. 
Thanks for the Help!
Norman
[libcamera Test-3-3.txt](https://github.com/raspberrypi/libcamera-apps/files/8182317/libcamera.Test-3-3.txt)
[log.txt](https://github.com/raspberrypi/libcamera-apps/files/8182318/log.txt)
[config.txt](https://github.com/raspberrypi/libcamera-apps/files/8182320/config.txt)

**Comment by davidplowman** [comment]
Just a few comments:

- I don't understand what "leaving allsky running" means. Only one thing can use the camera at once, so when that test script runs, there must be _no one else_ trying to do anything with the camera. Any other user of the camera must be stopped.
- I'm still trying to get the fix for the segfaults pushed up to apt. Hopefully soon now.
- When you increase the CMA, you have to do it exactly like I did: `dtoverlay=vc4-kms-v3d,cma-384` so that's no extra spaces and all lowercase. If the CMA numbers at the bottom of `cat /proc/meminfo` don't change then it's not right.

I'll let you know when apt has been updated, perhaps let's take it up again then.

**Comment by TexasTNT** [comment]
Understand, I fixed the syntax and now the cma has changed shutdown all other applications and now it runs but still gets the segfaults, so will wait on the apt to be updated.
Thanks for the Help!
Norman

**Comment by davidplowman** [comment]
So I believe there's a new version if you just do `sudo apt update` and `sudo apt install libcamera-apps`. Possibly we might push another version with a newer version of libcamera, but I think the version that's there now should fix the segfaults.

**Comment by TexasTNT** [comment]
Hello
looks like that fixed it no segfaults ran for hrs no issues. libcamera-jpeg also runs with no issues. Also noticed the update was pushed out.
Thanks again for the Help!
Norman
