### ISSUE TITLE
Wrong framerate written to video file

### ISSUE THREAD

**Issue by vwas2** [raspberrypi/libcamera-apps#290]
latest version when recording and replaying video on vlc media the codec info shows a framewrate of 30fps which means the actual parameter `--framerate 3` is **not written** to the video file. 

replicate eg by:
`libcamera-vid --timeout 10000 --framerate 3 -o test.h264`

this results in ugly replay experience that in this case compresses the 3*10 frames stretching over 10s into just 1s.

**Comment by davidplowman** [comment]
Hi, unfortunately this is the expected behaviour. The file written is an elementary h.264 stream which contains no framerate information. You would have to tell the playing software the correct framerate at which to play the video.

Alternatively, `libcamera-vid` can save frame timestamps and you can process the h.264 bitstream into a container format that includes the timestamps. One way to do that is illustrated [here](https://www.raspberrypi.com/documentation/accessories/camera.html#libcamera-vid).
