### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by knutegit** [raspberrypi/libcamera-apps#404]
New update to libcamera on RaspiOS64 today caused the stored file to be very low resolution.

[bug.txt](https://github.com/raspberrypi/libcamera-apps/files/9975533/bug.txt)
![test](https://user-images.githubusercontent.com/26259810/200953192-6e291a85-908a-4712-9399-54f33fab2b21.jpg)

**Comment by knutegit** [comment]
The same low resolution happens when the output is sent to stdout too.

**Comment by knutegit** [comment]
Problem doesn't appear on RaspiOS32 running on a Pi3B+ with an imx219 camera.

**Comment by knutegit** [comment]
Downloading and compiling from source eliminates the problem as well.

**Comment by naushir** [comment]
Thank you for the report.

I've just tried loading a fresh 64-bit OS image with a full update (``sudo apt update && sudo apt upgarde -y``), and I cannot seem to reproduce your problem.  Just to confirm, according to the bug report, you are running the following command:
```
libcamera-still -t 1000 -o test.jpg
```
is that correct?

Another thing that I noticed from your bug report was libcamera/libcamera-apps still seems to be on an older version:
```
** libcamera-still --version **
libcamera-apps build: 891c8fa973b9-intree 17-10-2022 (14:32:45)
libcamera build: v0.0.1+2-ae780930
```
It also shows this was compiled manually, rather than using the version in the apt repository.  On my updated build, I get:
```
pi@raspberrypi:~ $ libcamera-still --version
libcamera-apps build: 73ab09fcf408 09-11-2022 (14:58:13)
libcamera build: v0.0.1+54-d528119f
```

Would you be able to do an update (``sudo apt update && sudo apt upgarde -y``), and ensure any of your manually built instances of libcamera-apps have been removed  and try again?

**Comment by knutegit** [comment]
Doing the upgrade was how I got the weird results.  I can't reproduce the problem any more so there must have been something stuck in the update process.  Using the procedures from the docs to download and compile the libcamera(-apps) does that only put executables in the /usr/local/bin directory or does it put them other places too?

**Comment by knutegit** [comment]
I really don't understand what is going on.  I removed all of the libcamera executables from /usr/local/bin.  I purged libcamera0, libcamera-apps and libcamera-tools and then installed them again.  I get today's date when I check the version.

pi@raspberrypi64:~ $ whereis libcamera-still
libcamera-still: /usr/bin/libcamera-still

pi@raspberrypi64:~ $ libcamera-still --version
libcamera-apps build: 73ab09fcf408-intree 10-11-2022 (10:55:55)
libcamera build: v0.0.1+56-056da47e

Until I figure out what is going on I think you should just ignore this bug.  Sorry.

**Comment by knutegit** [comment]
I figured it out.  When you compile libcamera(-apps) it creates a bunch of libraries and stores them in /usr/local/lib/aarch64-linux-gnu.  Even if you run /usr/bin/libcamera-still it is still using those libraries which is where the --version is getting the number from.   So you have to delete the /usr/local/lib/aarch64-linux-gnu directory before you can use the apps from the repository.
