### ISSUE TITLE
FOV differences between camera modes

### ISSUE THREAD

**Issue by GuyPerets106** [raspberrypi/libcamera-apps#511]
Hi, I'm using RPi CM4 + Module 3 Wide cameras to record 640x400 100fps video and noticed something strange.
This is the output of `libcamera-vid --list-cameras` command:
![צילום מסך 2023-06-05 ב-12 29 58](https://github.com/raspberrypi/libcamera-apps/assets/79912473/6824948f-db87-4f67-b265-c43fd2c40b1a)

It first occured when I noticed a difference between libcamera-vid and libcamera-still which had very different FOVs. Later I found out online that the problem was caused by a missing`--mode` which will specify the full resolution of the sensor (12MP in my case), instead of letting the software "guess" the mode I need. The command I used and "fixed" the problem was:
`libcamera-vid --mode 4608:2592:10 --width 640 --height 400 -n --hdr 0 --denoise off --framerate 100 --frames 5000 -o test.h264`
**NOTE:** It works with the 2304x1296 mode too.

The main problem is that I need the full FOV but specifying a mode higher than 1536x864 causes frame skips which I can't really tolerate in my project. 
To be honest, I'm not even fully understand what's happening in the flow of the video stream - Why `--width 640 --height 400` still causes the camera to stream 4608x2592 frames and skip frames because of that?

There is a way of achieving full FOV from the cameras at 640x400 resolution with the `--mode` being 1536x864?

**Comment by naushir** [comment]
To start with your last question:

> There is a way of achieving full FOV from the cameras at 640x400 resolution with the `--mode` being 1536x864?

Unfortunately the answer is no if you want to achieve your 100fps target.  As the framerate from the sensor increases, we run into limitations of throughout with the pixel clock rate in the sensor, and what can be transmitted over the 2-lane CSI-2 bus.  So the higher framerate modes intentionally crop the frame's field of view in the sensor itself to active the target fps.

 > To be honest, I'm not even fully understand what's happening in the flow of the video stream - Why `--width 640 --height 400` still causes the camera to stream 4608x2592 frames and skip frames because of that?

With the command you have given above, specifying ``--width 640 --height 400`` with ``--mode 4608:2592:10`` instructs the pipeline to use the full sensor FoV  4608x2592 mode, and rescale that to generate a 640x400 output image from the ISP.  Since that the sensor can only produce (at most) 14.35 fps in that mode, this is the framerate you get on your output.

**Comment by GuyPerets106** [comment]
> The 2306x1296 mode will give you full horizontal FoV as it uses 2x binning in the sensor to generate the output, but you can only achieve a maximum of 56fps on the output.

And 1536x864 can't do that too with 3x binning? 
I'm not sure I even understand why FOV relates to resolution - One is the number of H/V pixels and the other is more of a lens property, isn't it? 
I imagine the FOV being a 'fixed' property and the resolution only determines the number of pixels in the same region of any frame.

**Comment by naushir** [comment]
> And 1536x864 can't do that too with 3x binning?

Some sensors can, but not the imx708.  This is a technical limitation in the sensor itself.

>I'm not sure I even understand why FOV relates to resolution - One is the number of H/V pixels and the other is more of a lens property, isn't it? I imagine the FOV being a 'fixed' property and the resolution only determines the number of pixels in the same region of any frame.

The choice of module lens does dictate FoV, as does the crop happening in the sensor.  Again, due to throughput limitations in the sensor or across the CSI-2 bus, we cannot read out every pixel in the full sensor array above a certain framerate.  This limitation is dictated by the pixel clock rate of the sensor itself.  So to achieve a higher framerate, we can only reduce the resolution of the sensor output mode, usually by programming a crop around the centre region of the pixel array.

**Comment by naushir** [comment]
Are there any further points to clarify here, or can I close this issue for now?
