### ISSUE TITLE
How are we supposed to compile the source code from now on?

### ISSUE THREAD

**Issue by FacuM** [raspberrypi/libcamera-apps#542]
The recently pushed commit 9e17265 implies that we shouldn't rely on CMake files anymore in order to build the project.

~~The supposedly well-known deprecation of the CMake-based compilation method hasn't really been documented at all, as far as I know at least and based off internet searches.~~ Edit: this is incorrect, I'm removing it.

My question is, then, how are we supposed to build it? The official blog post provided [here](https://www.raspberrypi.com/documentation/computers/camera_software.html#building-libcamera-apps) doesn't specify an alternative to the CMake-based compilation procedure.

I think this commit should either be **reverted** or a proper method be published ASAP in order to avoid breaking workflows that compile on bleeding-edge changes.

**Comment by naushir** [comment]
The documentation changes have already been made - see here: https://github.com/raspberrypi/documentation/pull/2992.
There's a wait on getting it published on the documentation website now, that's it.

I should note that since libcamera does not yet have a stable API/ABI, you will inevitably hit unavoidable breakages if you work on the bleeding edge of the tree.  This is why we publish official releases for our users.

**Comment by FacuM** [comment]
> The documentation changes have already been made - see here: [raspberrypi/documentation#2992](https://github.com/raspberrypi/documentation/pull/2992). There's a wait on getting it published on the documentation website now, that's it.
> 
> I should note that since libcamera does not yet have a stable API/ABI, you will inevitably hit unavoidable breakages if you work on the bleeding edge of the tree. This is why we publish official releases for our users.

Got it, thanks, I'm rewriting my build script now!
